kakanin	food,snack,delicacy,pie
imperyo	empire,imperium
arpia	harpia,harpy,harp
bakterya	bacteria
pakahulugan	to give meaning,definition,meaning,meaning or definition,connotation
pagpupunlay	fertilize,fertilization or seedlings,fertilization
ugali	attitude,character,habit as a result of custom, values, culture, norms, etc.,behavior,habit
peminismo	feminism
tropiko	tropical
panlapi	currency,affix,suffix,affixes
kalo	wheel,pulley
pisngi	cheek,cheeks
elektronika	electronics,electronic
aurista	aurist,otolaryngologists
pang-abay	adverb
kamay	hands,hand
kordata	chordate,chardata,chordata,chords
salot	plague,pest or plague,pest,epidemic,plaque
ampibyan	amphibian
ulap	clouds,cloud
likaw	spring,name of an accessory,spiral,coil
abulya	aboulia,ability,abulia,sickness
akustik	acoustic
peritonyo	peritoneum
nunal	mole
konsul	consul
supositoryo	suppository
balon	water well,well
herpetolohiya	herp,herpetology
aritmetika	mathematics,arithmatic,arithmetic
bertebrado	vertebrae,vertebrate,vertebrated
lantad	to expose,reveal,show,revealed,revelation
walang-hanggan	no end,infinite,indefinite,eternal,never-ending
makroekonomiya	macroeconomics,macro economy,macro economics
sinobitis	synovitis
eklipse	eclipse
tagtuyot	drought
elektron	electron
mapag-isa	alone,to be alone,lonely,recluse,loner
ratiles	berry (right word in tagalog is aratiles),berry
sona	sona,zone
noo	forehead
taluktok	summit,tip,peak,zenith,the top
tagapagpaganap	executive,representative,executor
kopa	chalice,grail,cup
katakawan	gluttony,glutony
utak	brain;,mind,brain
panulaan	poet,poem,threatre,poetry
sikmura	paunch,  maw,  stomach,stomach
palagay	thought,assumption,premise
dalawit	lever
salamangka	magic,wizardry
romansa	romance
bahay-bata	uterus,wumb,ovary,womb
ratan	rattan
halo	mixed,mix,mixture
mitolohiya	methology,meteorology,myth,mythology
banakal	fruit rind o tree bark,bark,fruit rind or tree bark
groto	grotto
paglikha	create,creation,to make,make,created
pamahiin	an old unproven belief,superstitious belief,superstition
tagaytay	crest,  range of mountains,  ridge,ridge
puki	gender,vagina
talaarawan	calendar,diary
pangangatwiran	justifying, justification,reasoning,justification
mikroskopyo	microscope,microscopic
alkoholismo	alcoholics,alcohol,alcoholism
katunggali	enemy,competitor,adversary,opponent
anak	child
globo	globe,blobal
kronika	cronics,chronic,cronic
pasma	muscle pain,spasm
anhiyoma	angioma
ulang	lobster
lamanlupa	gnome,creature
tiya	auntie,aunt
benigno	benigno
trikomonyasis	trichomoniasis
ruwisenyor	nightingale
homograpo	homograph
pagkit	wax
tiyo	uncle
ur	not a tagalog word
danaw	danao,the place where river water and salt sea water meets,lake,lagoon,this is where salt and river water meet,pond,lough
sugpo	prawn,prawns
piso	peso
biyolohiya	biology
yungib	cave
saltik	slingshot
bubong	roof
kakaw	cocoa,cacao,toucan
sakong	heels,heel
malarya	malaria
imahismo	imaginism,imagism
gago	fool,idiot,stupid
amerisyo	americium
puntod	tomb,sarcophagus,tombstone,grave
tsiko	name of a fruit, sapodilla,sapodilla
barya	coins,coin,change
biyenan	mother or father in-law,in law,mother-in-law,father/mother-in-law,in-laws (could refer to both mother and father in law),mother in-law,father or mother-in-law,mother in law,in-law,mother-in-law / father-in-law
isotopo	isotopes,isotope
laringhitis	laryngitis,laringitis
diyamante	dynamite,diamond,gem
metalurhiya	metallurgy,metrology
rekreasyon	recreation
lupa	soil,land
lumot	moss
bituin	star,stars
atay	liver
teknolohiya	technology
asetabulum	acetabulum
dagsin	pull,gravity
puson	lowe abdomen,abdomen
aliterasyon	alliteration,aliteration
hematita	hematite
hayop	animal
lawin	hawk
pelikano	pelican,pelican bird
tutubi	firefly,dragonfly,dragon fly
bisiro	pony
bosyo	goitre,goiter,growth in thyroid gland
duyong	seacow,sea cow
losyon	lotion
kardiolohiya	cardiology
salita	word
kalesa	carriage,barouche
lagnaw	whey protein,whey,whey, milk serum,liquid,whey milk serum
balanopostitis	balanopostite,balanopostitis,balanitis,balanoposthitis
barometro	barometer
kasoy	cashew nut,cashew
likido	lilquid,liquid
kalabaw	carabao,water buffalo,buffalo
ahedres	chess
pangulo	president
buhay	life
sakit	desease,pain,ailment,sickness
tunog	sound,sounds
paghihinang	to weld,welding
pakpak	wings,wing
hidroheno	hydrogen
pagdaragdag	addition
tanghalan	theater,theatre,stage
temperatura	temperature
bubuwit	newly born mouse,mouse,mouse, small,small mouse
musaka	musaka,moussaka
asetanilido	acetanilide
binga	pearl,nacre,mother of pearl
relatibidad	relativity
kasubha	saffron
akyut	acute,less than 90°, sensitive to details; keen
punungkatawan	body,whole body,torso,principle body,trunk
humus	hummus,humus,sweet garbanso desert
boltahe	voltage
tabak	ax,sword
salaysay	essay,a story told,story,speech,story,statement,narrative
kongreso	congress
pabula	parable,fable
mistisismo	mystical,mysticism,myticism,mistisism
kusilba	fossil
lokasyon	location
akustika	acoustic,acoustics
pagkain	food,eat,food (noun) or eating (verb)
astronota	astronaute,astronota,astronaut,astonaut
harana	serenade,courtship,seranade
iktiyolohiya	ichthyology,ichtyology,ictiology
artikulasyon	article,articulation
kasuwapangan	selfishness,selfish,greed,greedy
kaktel	coctail,cocktail
ibon	bird
piyo	gout
paypay	scapula
suha	pomelo,pomelo or chinese grapefruit,grapefruit,lemon
pulo	island,islet
hinekomastiya	gynecomastia
direktor	director
nilalang	being,being, creature,a being, creature,creature
talingting	talint,plover
katamaran	laziness
ulo	head
kuting	kitten,cat
silogismo	silogism,syllogism,silogismo
mukha	face
kamera	camera
pagkatao	humanity,personality
karamdaman	illness or disease,illness,disease,sickness
kard	card
abasto	baggage,luggage
dalya	dahlia
daliri	finger
ilong	nose
balakang	hip
lawak	wide,area,space,width,wideness,scope,vast
paninilaw	yellowish,yellowing or jaundice,jaundice,yellowing
pipit	sparrow
pagtutuos	accounting,accountancy
etnosentrismo	ethnocentric,ethnocentrism,etnocentrism
humero	humerus
manunulat	writer,writter,author
imperyalismo	imperialism
pusit	squid
buni	ringworm,rash
langgam	ant,ants
eskriba	scribe,an interpreter of the law
bakuna	vaccination,vaccine
astropisika	astrophysics,astronomy
awitin	song
paa	foot,feet,leg
bukung-bukong	ankle,joints
pananahi	sew,seaming,tailoring,sewing,weaving
kamao	fist or punch,fist
tagapagbatas	legislature,legislative,lawmaker,justice,lawmaking,law maker,prosecutor
aguot	grunt (fish),grunts(fish),grunt
tako	taco,tacos
pekas	blackheads,freckles,blackhead,frecles
transmutasyon	mutation,transmutation
alupihan	centipede
nakaraan	past
kalansay	skeleton
ngipin	tooth,teeth
asukal	sugar
tagukan	glottis,tonsil,glotis
agham	science
kosmogoniya	cosmogony,cosmogeny
beterinaryo	veterinary,veterinarian
gagamba	spider
tagilo	pyramid
daktilo	dactyl,toes
pait	gouge,chisel
karang	atoll
gulang	age
paraiso	heaven,paradise
pagtalon	jump,to jump,jumping
manggagapang	creeper,groveller
ekskresyon	excretion,excertion
dagat	sea; ocean,sea,ocean
uranyo	uranium
kulay	color,colour
tintura	tint,a cooking technique,tincture
epikureanismo	epicurenism,epicureanism
bulak	cotton
tiyaga	patience
pangkalikol	probe
bedelyo	bdellium,bedellium
merkuryo	mercury
kasalukuyan	current,at this time,right now,present time,present
parola	lighthouse,light house,beacon
