feromon	pheromone
inersia	the inertia,inertia
kalori	calorie,calory
pemindahan	transfer
koma-koma	safron,saffron
pengguna	user,user / consumer,users
kubus	cube
aisberg	iceberg
jin	genie
hidrografi	hydrographic,hydrography,hydrogrpahy
gigi	teeth,gear,tooth
udang	prawn,shrimp
nelayan	sailor,fisherman
bersyukur	be grateful,thankfulness / gratefulness,grateful,thankful
rejam	stoning
makroekonomi	macroeconomics,macro economy,macroeconomic,macro-economy,macro economic
arteri	artery,arteries
jururawat	nurses,nurse
kripton	krypton
makanan	food,food  food  food
konflik	conflict
selang-seli	alternating,criss cross
jerebu	haze
perut	stomach
hidupan	life
gerhana	eclipse
chordata	chordate,chordata
kopra	copra
alkoholisme	alcoholism,alkoholism
polisakarida	polysaccharides,polysaccharide
zirkonium	zirconium,zirkonium
alkuna	alkynes,alkyne
penghala	router,router  router
tekanan	pressure
kritikan	criticism,critique,criticsm
makam	tomb,tomb / mausoleum
semut	ant,ants
antibiotik	antibiotics,antibiotic
heteroseksual	heterosexual
toraks	thoracic,toraks,the thorax,thorax
warna	color,colour,colors
bodoh	stupidity,stupid
frekuensi	frequency
pedofilia	pedophilia,pedophile,pedofile,pedophiles
angkasawan	astronaut
pecutan	accleration,acceleration,accelaration
mus	mouse
anglofilia	anglophile,anglophilia
tifus	typhoid,typhus,tifus,typhos
skandium	scandium
unsur	element
bebaling	propeller,bebaling
berlian	diamond
awan	clouds,cloud
penyapu	broom
gonggok	caterpillar,millipedes,millipede
aritmetik	arithmetic
tanah	soil,land
teknologi	technology
termosfera	thermosphere,termosphere
pedang	sword
elektronik	electronics,electronic
bakteria	bacteria,bacterium
lagu	song
pengkristianan	cristian,christianity
perakaunan	accounting,accountancy
keluasan	area,area(width),width,wide,vastness
amina	amines,amine
astrofizik	astrophysics,astro physics
kriptografi	cryptographic,cryptography
kerbau	buffalo,ox
jejari	radius,radial
ulama	muslim scholar,islamic scholar
celur	blanch,scalded,blanching,scald
sains	science
reptilia	repitiles,reptile,reptiles
kemerdekaan	independence
singgahsana	throne,rest stop
mistisisme	mysticism,of mysticism,mystisism,myticism
nukleotida	nucleotides,the nucleotide,nucleotide
labah-labah	spider,spider bee
dermaga	dock,wharf,port
filateli	philatelic,philately
yahudi	jewish,jew,jews
kimpalan	weld,welding
skalar	scalar,scale
tinja	excrement,defecate,feces,waste / excrement,waste / excretion
biopemulihan	biorecovery,bio recovery
kemarau	dry,drought
pelabuhan	harbor , port , dock,port
pedagogi	pedagogy
perkumuhan	excretion
zetabit	zetabit,zetabyte
betik	papaya
fonetik	phonetic,phonetics
kamera	camera
tuisyen	tution,tuition
hidrogen	hydrogen
petir	lighting,lightning
serafim	the seraphim,seraphim
prosa	prose
penyakit	illness,disease
antropogen	anthropogenic
catur	chess
pulau	island
voltan	voltage
benih	seed,seeds
graviti	gravity
minit	minutes,minute
gigabait	gigabit,gigabyte
lanca	,rickshaw
antizarah	antizarat,antiparticle,anti particle,anti-atomic
terusan	canal
timah	tin,lead
rangka	framework,frame,skeleton
burung	bird
pukimak	scandium,curse your mother,curse word, literally "mother's genitals", equivalent to 'motherfucker',mother fucker
bioperubatan	biomedicine,biomedical
gelora	turbulence
glukagon	glucagon
rekreasi	recreation
termokimia	thermochemistry,the thermochemical,thermochemical
